### ISSUE TITLE
export htmlWriter for use with Reader/Writer

### ISSUE THREAD

**Issue by u0nel** [robert-nix/ansihtml#2]
As `Parser` is exported, it doesn't seem to make sense to not also export `htmlWriter`, as it seems to be required to use the parser.

**Comment by robert-nix** [comment]
`htmlWriter` is intended to just be the internal implementation of `ConvertToHTML[WithClasses]`; `Parser` only interacts with it through the `escapeHandler` func passed to `Parse`, so if you want to output a different format, creating a new implementation with an `escapeHandler` is the intended way.  If you need more customization or more escape support in the HTML converter, I'd rather that be done as a PR to this library than forcing downstream consumers to reimplement portions of `htmlWriter`.
